drop table public.beer;
drop table public.coffee;
drop table public.food;
drop table public.dessert;
drop table public.albums;

create table public.beer
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	brand text,
	name text,
	style text,
	hop text,
	yeast text,
	malts text,
	ibu text,
	alcohol text,
	blg text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.coffee
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	blend_name text,
	origin text,
	variety text,
	notes text,
	intensifier text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.food
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	dish text,
	description text,
	ingredient text,
	measurement text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.dessert
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	variety text,
	topping text,
	flavor text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.albums
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    artist_id bigint,
	album_title text,
	genre text,
	year_of_pub bigint,
	num_of_tracks bigint,
	num_of_sales bigint,
	rolling_stone_critic bigint,
	mtv_critic bigint,
	music_maniac_critic bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);